name: Update Flake and UV
on:
  schedule:
    - cron: "00 5 * * MON"
  workflow_dispatch:

jobs:
  Update-Flake-UV:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - name: Update UV lock file
        run: uv lock --upgrade
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore: update nix flake inputs"
          token: ${{ secrets.PR_TOKEN }}
